//
//  TubFeedbacks.swift
//  BlueIOSNew
//
//  Created by Opportunity on 10/04/23.
//

class BathTubFeedbacks {
    
    static let FIRMWARE = "f"
    static let VERSION = "v"
    static let QT_BOMBS = "quantbombas"
    static let WATER_CTRL = "agua"
    static let BT_ID = "BTid"
    static let TEMP_OFFSET = "tempoffset"
    static let LEVEL1_OFFSET = "tempoN1"
    static let LEVEL2_OFFSET = "tempoN2"
    static let WIFI_STATE = "estadoWifi"
    static let SSID = "ssid"
    static let PSWD = "passwd"
    static let IP = "ip"
    static let BACKLIGHT = "backlit"
    static let GET_TEMPOFF = "tempoffset"
    static let GET_TN1 = "tempoN1"
    static let GET_TN2 = "tempoN2"
    static let FT_DAYS = "agendaDias"
    static let FT_HOUR = "agendaHor"
    static let FT_MIN = "agendaMin"
    static let FT_TIME = "agendaTempo"
    static let BH_DAYS = "agendaBanhoDias"
    static let BH_HOUR = "agendaBanhoHor"
    static let BH_MIN = "agendaBanhoMin"
    static let BH_TEMP = "agendaTemperatura"
    static let FL_TIME = "tempoParaEncher"
    static let WM_TIME = "tempoParaAquecer"
    static let LOGO = "logo"
    static let POWER = "power"
    static let TEMP_NOW = "tempAgua"
    static let TEMP_DESIRED = "tempset"
    static let BOMB1_STATE = "saida01"
    static let BOMB2_STATE = "saida02"
    static let BOMB3_STATE = "saida03"
    static let BOMB4_STATE = "saida04"
    static let BOMB5_STATE = "saida05"
    static let COOLING = "resfriando"
    static let KEEP_WARM = "manterQuente"
    static let HEATER_STATE = "aquecedor"
    static let LEVEL_STATE = "nivel"
    static let QT_SPOTLEDS = "spotsQuantLEDs"
    static let QT_STRIPLEDS = "fitaQuantLEDs"
    static let SPOTS_STATE = "spotsEstado"
    static let SPOTS_COLOR = "spotsCor"
    static let SPOTS_SPEED = "spotsVel"
    static let SPOTS_BRIGHT = "spotsBrilho"
    static let SPOTS_COLORMODE = "spotsPadrao"
    static let STRIP_STATE = "fitaEstado"
    static let STRIP_COLOR = "fitaCor"
    static let STRIP_SPEED = "fitaVel"
    static let STRIP_BRIGHT = "fitaBrilho"
    static let STRIP_COLORMODE = "fitaPadrao"
    static let MQTT_PUB = "mqttPUB"
    static let MQTT_SUB = "mqttSUB"
    static let MQTT_STATE = "mqttStatus"
    static let TMP_PSWD = "senhaTemporaria"
    static let TUB_PSWD1 = "senha01"
    static let TUB_PSWD2 = "senha02"
    static let TUB_PSWD3 = "senha03"
    static let TUB_PSWD4 = "senha04"
    static let TUB_NPSWD = "quantSenhas"
    static let MSG_CODE = "msg_num"
    static let LAST_ON = "alive"
    static let PSWD_ERR = "senha"
    static let STATUS_M1 = "m1_status"
    static let NAME_M1 = "m1_nome"
    static let STATUS_M2 = "m2_status"
    static let NAME_M2 = "m2_nome"
    static let STATUS_M3 = "m3_status"
    static let NAME_M3 = "m3_nome"
    static let STATUS_M4 = "m4_status"
    static let NAME_M4 = "m4_nome"
    static let STATUS_M5 = "m5_status"
    static let NAME_M5 = "m5_nome"
    static let DRAIN_MODE = "modoacionamentoralo"
    static let DRAIN_TIME = "tempoparaesvaziar"
    
    static let HAS_HEATER = "saidaAquecedor"
    static let HAS_WATER_CTRL = "saidaauxconf"
    static let AUTO_ON = "ligaAutom"
    static let HAS_TEMP = "sensortemp"
    static let HAS_CROMO = "saidaRGBA"
    static let HAS_DRAIN = "controleralo"
    static let GET_SPOT_CMODE = "spotPadraoCor"
    static let GET_STRIP_CMODE = "fitaPadraoCor"
}
